"""
Road Trip Cost Predictor - FastAPI backend.

Serves a CHAINED MODEL PIPELINE over 537 Indian cities: two city names, a vehicle, a fuel type
and a departure time go in; a cost estimate with a full breakdown comes out. Every intermediate
quantity - road distance, fuel efficiency, litres burnt, toll, traffic level - is predicted by
its own fitted sub-model rather than computed from a hardcoded constant. See the note below the
imports for what those constants were, and scripts/train_pipeline.py for how each was replaced.

    python scripts/build_cities.py          # 3739 cities with real lat/lon
    python scripts/build_fuel_prices.py     # per-state fuel prices
    python scripts/build_wide_dataset.py    # 25,000 trips over real geography
    python scripts/fetch_real_distances.py  # 840 REAL road distances from OSRM
    python scripts/train_models.py          # -> models/model.joblib   (Week 6 regressor)
    python scripts/train_pipeline.py        # -> models/pipeline.joblib (the six sub-models)
    uvicorn app:app --reload                # -> http://127.0.0.1:8000

Endpoints
    GET  /api/cities?q=          city autocomplete (name or state), with the state's fuel prices
    GET  /api/default-mileage    what the mileage sub-model predicts for a vehicle + fuel
    POST /api/predict            cost regression + band and traffic classification
    POST /api/departure-sweep    expected cost across all 24 departure hours
    GET  /api/loss-curve         gradient-descent curve + sklearn comparison
    GET  /api/metrics            honest test-set metrics for the report-card section
    GET  /api/health             liveness
"""
from __future__ import annotations

import json
import math
import os
import urllib.error
import urllib.request
from functools import lru_cache
from typing import Literal, Optional

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

import roadtrip_features as rf

ROOT = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(ROOT, "models", "model.joblib")
PIPELINE_PATH = os.path.join(ROOT, "models", "pipeline.joblib")
CITIES_PATH = os.path.join(ROOT, "data", "india_cities.csv")
FUEL_PATH = os.path.join(ROOT, "data", "fuel_prices.csv")
STATIC_DIR = os.path.join(ROOT, "static")

# --- what used to be here -----------------------------------------------------------
# Five hardcoded constants did the real work of this API, and only the final addition was
# a model:
#
#     WINDING_FACTOR = 1.2355     haversine -> road km
#     TRAFFIC_MULT   = {...}      fuel burn by traffic level
#     TOLL_RATE      = 1.301      Rs/km
#     DEFAULT_PARKING = 70.0
#     MAINTENANCE    = {...}      Rs/km by vehicle
#
# Each is now a fitted sub-model in models/pipeline.joblib, trained and scored by
# scripts/train_pipeline.py. The winding factor mattered most: measured against 840 real OSRM
# road distances it is nearly unbiased on average but wrong by 6.3% on a typical single route,
# and by up to 260% where geography intervenes (Surat -> Bhavnagar is 94 km straight and 339 km
# by road, around the Gulf of Khambhat). A user takes one trip, not the average of all of them.
#
# TWO CONSTANTS REMAIN, deliberately:
#   TRAFFIC_MIN_PER_KM  travel TIME, which this project never modelled - it is not part of the
#                       cost target, so fitting it would be inventing scope. Labelled, not hidden.
#   MIN/MAX_TRAINED_KM  the training range, used only to warn about extrapolation.
TRAFFIC_MIN_PER_KM = {"Low": 0.919, "Medium": 1.059, "High": 1.263}    # travel time, NOT modelled
MIN_TRAINED_KM, MAX_TRAINED_KM = 50.0, 1500.0
OSRM_URL = "http://router.project-osrm.org/route/v1/driving/{},{};{},{}?overview=false"
OSRM_TIMEOUT = 4.0

VehicleType = Literal["Hatchback", "Sedan", "SUV"]
FuelType = Literal["Petrol", "Diesel", "CNG"]
TrafficLevel = Literal["Low", "Medium", "High"]

app = FastAPI(title="Road Trip Cost Predictor", version="1.0")
app.add_middleware(
    CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"]
)

# joblib.load unpickles, so it must only ever be pointed at files this repo produces itself.
# Both paths below are generated by scripts/ in this project and committed alongside it; no
# model file is ever fetched from a remote or user-supplied location.
#
# Two bundles, on purpose.
#   BUNDLE  models/model.joblib     - the Week 6 cost regressor, the cost-band classifier and
#                                     the gradient-descent history the /api/loss-curve endpoint
#                                     serves. Kept so the notebook's Week 3-8 story stays live.
#   PIPE    models/pipeline.joblib  - the six sub-models that replaced the constants, plus the
#                                     chained cost regressor trained on their predictions.
BUNDLE = joblib.load(MODEL_PATH)
PIPE = joblib.load(PIPELINE_PATH)
CITIES = pd.read_csv(CITIES_PATH)
FUEL = pd.read_csv(FUEL_PATH).set_index("state")

# The models were trained on cities with population >= 100k; only those are in-domain.
IN_DOMAIN = CITIES[CITIES.population >= 100_000].reset_index(drop=True)
CITY_INDEX = {
    (r.city.lower(), r.state.lower()): r for r in IN_DOMAIN.itertuples(index=False)
}


# --------------------------------------------------------------------------- helpers
def haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    r = 6371.0088
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = p2 - p1
    dl = math.radians(lon2 - lon1)
    h = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(h))


def model_distance_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Road distance from the fitted distance model - sub-model 1, the offline fallback.

    Trained on 840 real OSRM road distances (data/real_distances.csv), so unlike the constant
    it replaces this has actually seen Indian road geometry. It predicts the WINDING FACTOR and
    multiplies by haversine, rather than predicting kilometres directly: that keeps the target
    scale-free, so the model spends its capacity on the part that is genuinely unknown - the
    shape of the route - instead of re-learning "longer straight line, longer road".
    """
    x = np.array([rf.distance_features(lat1, lon1, lat2, lon2)], dtype=float)
    predicted = float(PIPE["distance_model"].predict(x)[0])
    if PIPE["distance_parameterisation"] == "factor":
        predicted *= haversine_km(lat1, lon1, lat2, lon2)
    return round(predicted, 2)


@lru_cache(maxsize=4096)
def road_distance_km(lat1: float, lon1: float, lat2: float, lon2: float) -> tuple[float, str]:
    """Real road distance via OSRM, falling back to the fitted distance model.

    Live routing is still preferred - a real answer beats a predicted one whenever it is
    available. The change is what happens when it is not: the fallback used to be
    `haversine x 1.2355`, and is now a model whose held-out error is known (RMSE 46.6 km vs
    53.1 km for the constant, MAE 30.7 km vs 34.3 km - a 10.7% reduction).
    """
    try:
        url = OSRM_URL.format(lon1, lat1, lon2, lat2)
        req = urllib.request.Request(url, headers={"User-Agent": "roadtrip-predictor/1.0"})
        with urllib.request.urlopen(req, timeout=OSRM_TIMEOUT) as resp:
            payload = json.loads(resp.read())
        if payload.get("code") == "Ok" and payload.get("routes"):
            return round(payload["routes"][0]["distance"] / 1000.0, 2), "osrm"
    except (urllib.error.URLError, TimeoutError, ValueError, KeyError, OSError):
        pass  # network unavailable or rate-limited - fall through to the model
    return model_distance_km(lat1, lon1, lat2, lon2), "distance_model"


def default_mileage(vehicle: str, fuel: str) -> float:
    """Fuel efficiency from the mileage model - sub-model 2.

    Replaces asking every user for their own km/l, or defaulting all nine (vehicle, fuel)
    combinations to a single 15.5. Honest ceiling: the training data draws mileage uniformly
    inside a per-combination range, so the best any model can do is name the middle of the
    right cell - test R2 0.673, and the rest is irreducible.
    """
    x = np.array([rf.mileage_features(vehicle, fuel)], dtype=float)
    return round(float(PIPE["mileage_model"].predict(x)[0]), 2)


def predict_litres(distance: float, mileage: float, traffic: str) -> float:
    """Fuel consumed, from the litres model - sub-model 3. Replaces TRAFFIC_MULT."""
    x = np.array([rf.litres_features(distance, mileage, traffic)], dtype=float)
    return round(float(PIPE["litres_model"].predict(x)[0]), 3)


def predict_toll(distance: float) -> float:
    """Toll, from the toll model - sub-model 4. Replaces TOLL_RATE = 1.301.

    Honest ceiling: the training data sets toll = distance x N(1.301, 0.360), so the RATE is
    recoverable but the per-trip spread is noise. Test R2 0.795, and the residual RMSE of about
    Rs 212 cannot be reduced by any model on this data.
    """
    x = np.array([rf.toll_features(distance)], dtype=float)
    return round(max(0.0, float(PIPE["toll_model"].predict(x)[0])), 2)


# Sub-model 5, parking, is deliberately absent. Six model families were fitted and every one
# scored test R2 <= 0 - worse than predicting the mean - because the training data draws parking
# uniformly from {0, 40, 60, 80, 120, 150} independently of everything else. A model with
# negative R2 has no business in a prediction path, so the training-set mean is served instead
# and the negative result is reported rather than buried. See scripts/train_pipeline.py.
DEFAULT_PARKING = round(float(PIPE["parking_mean"]), 2)


def recovered_traffic_multipliers() -> dict:
    """The fuel-burn multipliers, read back out of the fitted litres model.

    The old code hardcoded {"Low": 0.944, "Medium": 1.045, "High": 1.165}. These are the same
    numbers, but measured from the model at startup rather than asserted: litres is linear in
    (distance / mileage), so the multiplier for a traffic level is just the slope of litres
    against that ratio. Probing the model for two distances recovers it.
    """
    out = {}
    mileage = 15.5
    for level in ("Low", "Medium", "High"):
        one = predict_litres(mileage * 1.0, mileage, level)      # ratio = 1
        two = predict_litres(mileage * 2.0, mileage, level)      # ratio = 2
        out[level] = round(two - one, 3)
    return out


TRAFFIC_MULT = recovered_traffic_multipliers()


def resolve_city(name: str, state: Optional[str] = None):
    key_name = name.strip().lower()
    if state:
        hit = CITY_INDEX.get((key_name, state.strip().lower()))
        if hit is not None:
            return hit
    matches = IN_DOMAIN[IN_DOMAIN.city.str.lower() == key_name]
    if matches.empty:
        raise HTTPException(404, f"City not found in the model's 537-city domain: {name!r}")
    # ambiguous name -> largest city wins
    return matches.sort_values("population", ascending=False).iloc[0]


def fuel_price_for(state: str, fuel: FuelType, override: Optional[float] = None):
    """Resolve the price per litre, preferring what the user actually told us.

    Only 6 of 35 states have a verified price; the rest are estimates. Someone filling their own
    tank knows the real number better than this table does, so a supplied value always wins and
    is reported as source="user" — which also suppresses the estimated-price warning, because
    with a real figure there is nothing left to caveat.
    """
    if override is not None:
        return float(override), "user"
    if state in FUEL.index:
        row = FUEL.loc[state]
        return float(row[fuel.lower()]), str(row["source"])
    return 107.5, "fallback"


def state_fuel_prices(state: str) -> dict:
    """All three prices for a state, so the UI can prefill the field the moment a city is
    chosen instead of making another round trip."""
    if state in FUEL.index:
        row = FUEL.loc[state]
        return {
            "petrol": float(row["petrol"]), "diesel": float(row["diesel"]),
            "cng": float(row["cng"]), "source": str(row["source"]),
        }
    return {"petrol": 107.5, "diesel": 99.8, "cng": 84.5, "source": "fallback"}


def traffic_features(hour: int, month: int) -> np.ndarray:
    """Cyclical encoding, matching training. Hour is fed as sin/cos rather than 0-23 so the
    model does not treat 23:00 and 00:00 as maximally distant."""
    return np.array([rf.traffic_features(hour, month)], dtype=float)


def predict_traffic(hour: int, month: int) -> str:
    """Traffic level, from the traffic classifier - sub-model 6."""
    return str(PIPE["traffic_model"].predict(traffic_features(hour, month))[0])


def estimate_cost(distance, mileage, fuel_price, parking, traffic, vehicle):
    """Core cost computation, shared by /api/predict and /api/departure-sweep.

    Returns (litres, toll, total). Every intermediate value now comes from a sub-model rather
    than from a constant, and the final regressor was TRAINED on sub-model predictions rather
    than on ground truth - which matters more than it sounds.

    Fitting the cost model on true toll/parking/litres and then serving it predicted ones is a
    train/serve mismatch: the model learns to trust inputs that are exact and then receives
    inputs that are not. scripts/train_pipeline.py measures both ways, and the chain-consistent
    model (trained out-of-fold on its own sub-models' predictions) is the one loaded here.

    Litres and toll stay DERIVED, never asked for. A traveller cannot know their fuel
    consumption before setting off, and it is the regressor's strongest feature - which is
    exactly why handing it in inflated the old R2. See FINDINGS.md.
    """
    litres = predict_litres(distance, mileage, traffic)
    toll = predict_toll(distance)

    x = np.array([rf.cost_features(distance, mileage, fuel_price, toll, parking, litres,
                                   vehicle)], dtype=float)
    total = float(PIPE["cost_model_chained"].predict(x)[0])
    return litres, toll, total


def predict_band(distance, mileage, fuel_price, toll, parking, litres,
                 vehicle: str, fuel: str, traffic: str) -> str:
    frame = pd.DataFrame([{
        "distance_km": distance, "mileage": mileage, "fuel_price": fuel_price,
        "toll_cost": toll, "parking_cost": parking, "fuel_consumption_litres": litres,
        "vehicle_type": vehicle, "fuel_type": fuel, "traffic_level": traffic,
    }])
    encoded = pd.get_dummies(frame, columns=BUNDLE["band_categorical"], drop_first=True)
    encoded = encoded.reindex(columns=BUNDLE["band_columns"], fill_value=0)
    scaled = BUNDLE["band_scaler"].transform(encoded.values.astype(float))
    return str(BUNDLE["band_classifier"].predict(scaled)[0])


# ---------------------------------------------------------------------------- schemas
class PredictRequest(BaseModel):
    start_city: str
    destination_city: str
    start_state: Optional[str] = None
    destination_state: Optional[str] = None
    vehicle_type: VehicleType = "Sedan"
    fuel_type: FuelType = "Petrol"
    mileage: Optional[float] = Field(
        None, gt=3, lt=60,
        description="km per litre. Omit and the mileage sub-model fills it in from the "
                    "vehicle and fuel type, so you are never asked for a number you may "
                    "not know.",
    )
    departure_hour: int = Field(9, ge=0, le=23)
    month: int = Field(6, ge=1, le=12)
    traffic_level: Optional[TrafficLevel] = Field(
        None, description="omit to have the traffic classifier infer it from hour and month"
    )
    fuel_price: Optional[float] = Field(
        None, gt=30, lt=300,
        description="rupees per litre (per kg for CNG). Omit to use the per-state table, "
                    "which is verified for only 6 of 35 states.",
    )
    parking_cost: Optional[float] = Field(None, ge=0, le=2000)
    passengers: int = Field(4, ge=1, le=8)


# ----------------------------------------------------------------------------- routes
@app.get("/api/health")
def health():
    return {"status": "ok", "cities": len(IN_DOMAIN), "model": os.path.basename(MODEL_PATH)}


@app.get("/api/metrics")
def metrics():
    """Honest test-set numbers. The UI shows these verbatim - do not round them up.

    This endpoint used to report R2 = 0.999707 as the accuracy of a prediction. That number is
    real but it does not describe what a user receives: it was measured with the true toll,
    parking and litres handed to the model as inputs, and a user supplies none of those. What
    they get is the chained pipeline, which starts from two city names.

    Both are reported, labelled, with the gap between them stated. The headline the UI should
    quote is `served`.
    """
    pm = PIPE["metrics"]
    m = dict(BUNDLE["metrics"])

    served = pm["cost_chained"]
    fed = pm["cost_true_components"]
    m["served"] = {
        "what": "chained pipeline: two city names + vehicle + fuel + departure time",
        "r2": served["r2"], "rmse": served["rmse"], "mae": served["mae"],
        "note": "This is what a prediction from this API is worth.",
    }
    m["fed_true_components"] = {
        "what": "the same cost regressor, given the true toll, parking and litres",
        "r2": fed["r2"], "rmse": fed["rmse"], "mae": fed["mae"],
        "note": ("Kept for comparison, not as a headline. It answers 'given the litres burnt "
                 "and the toll paid, can you add them up?' - which is not the user's question."),
    }
    m["honesty_gap"] = {
        "r2": round(fed["r2"] - served["r2"], 6),
        "mae_rupees": round(served["mae"] - fed["mae"], 2),
        "note": ("The cost of asking the model to derive its own inputs instead of being "
                 "handed them. This gap IS the finding, not an embarrassment."),
    }
    m["sub_models"] = {
        "distance": {
            "trained_on": f"{pm['n_real_distance_pairs']} real OSRM road distances",
            "r2": pm["distance_real"]["r2"], "rmse_km": pm["distance_real"]["rmse"],
            "mae_km": pm["distance_real"]["mae"],
            "constant_baseline_mae_km": pm["distance_constant_baseline"]["mae"],
            "note": ("Replaces the hardcoded winding factor 1.2355. The only sub-model trained "
                     "on observed rather than generated data."),
        },
        "parking": {
            "note": ("NEGATIVE RESULT: six model families all scored test R2 <= 0, because "
                     "parking is drawn uniformly at random in the training data. The mean is "
                     "served instead of a model."),
        },
        "traffic": pm["traffic"],
        "error_budget": pm["error_budget"],
    }
    m["geography_bias"] = pm["geography_bias"]
    m["notes"] = {
        "regression": "Linear regression including the litres x price interaction term.",
        "band": ("cost_band is a quartile split of Rs/km, which the regressor already predicts "
                 "well, so this accuracy is high by construction."),
        "traffic": ("Genuinely non-trivial: traffic is only partly determined by departure hour, "
                    "so the ceiling here is low. Compare against the majority baseline."),
        "served_vs_fed": ("Quote `served`. `fed_true_components` is the older, larger number "
                          "and it measures a different question."),
    }
    return m


@app.post("/api/departure-sweep")
def departure_sweep(req: PredictRequest):
    """Predicted cost for every one of the 24 departure hours on the same route.

    This is what makes the traffic classifier do real work. In the main prediction it produces
    a single word; here it drives 24 predictions and answers a question a traveller actually
    has — "when should I leave?"

    traffic_level is ignored if supplied: the whole point is to let the classifier infer it per
    hour. Distance is resolved once (and cached), so this is 24 cheap model calls, not 24 routing
    round-trips.
    """
    origin = resolve_city(req.start_city, req.start_state)
    dest = resolve_city(req.destination_city, req.destination_state)
    if (origin.city, origin.state) == (dest.city, dest.state):
        raise HTTPException(400, "Start and destination must be different cities.")

    distance, distance_source = road_distance_km(
        float(origin.lat), float(origin.lon), float(dest.lat), float(dest.lon)
    )
    fuel_price, _ = fuel_price_for(origin.state, req.fuel_type, req.fuel_price)
    parking = DEFAULT_PARKING if req.parking_cost is None else req.parking_cost
    mileage = (req.mileage if req.mileage is not None
               else default_mileage(req.vehicle_type, req.fuel_type))

    # Expected cost, not argmax cost.
    #
    # Taking the classifier's single most likely traffic level gives a 3-level step function —
    # every hour collapses onto one of three values, which hides everything the model actually
    # knows. Weighting each level by its predicted probability gives a smooth curve that
    # reflects the classifier's real confidence: an hour that is 55% High reads differently
    # from one that is 95% High, and it should.
    clf = BUNDLE["traffic_classifier"]
    levels = list(clf.classes_)

    hours = []
    for hour in range(24):
        probs = clf.predict_proba(traffic_features(hour, req.month))[0]
        per_level = {
            level: estimate_cost(distance, mileage, fuel_price, parking,
                                 level, req.vehicle_type)
            for level in levels
        }
        expected_cost = sum(p * per_level[l][2] for l, p in zip(levels, probs))
        expected_litres = sum(p * per_level[l][0] for l, p in zip(levels, probs))
        expected_minutes = sum(
            p * distance * TRAFFIC_MIN_PER_KM[l] for l, p in zip(levels, probs)
        )
        modal = levels[int(np.argmax(probs))]

        hours.append({
            "hour": hour,
            "traffic_level": modal,
            "traffic_confidence": round(float(max(probs)), 3),
            "traffic_probabilities": {l: round(float(p), 3) for l, p in zip(levels, probs)},
            "total_trip_cost": round(expected_cost, 2),
            "fuel_consumption_litres": round(expected_litres, 3),
            "estimated_time_minutes": round(expected_minutes, 1),
        })

    cheapest = min(hours, key=lambda h: h["total_trip_cost"])
    dearest = max(hours, key=lambda h: h["total_trip_cost"])

    return {
        "route": {
            "from": {"city": origin.city, "state": origin.state},
            "to": {"city": dest.city, "state": dest.state},
            "distance_km": distance,
            "distance_source": distance_source,
        },
        "hours": hours,
        "cheapest": cheapest,
        "dearest": dearest,
        "max_saving": round(dearest["total_trip_cost"] - cheapest["total_trip_cost"], 2),
        "note": (
            "Cost varies with departure hour only through traffic, which changes how much fuel "
            "is burnt. Tolls, parking and distance are unaffected."
        ),
    }


@app.get("/api/loss-curve")
def loss_curve():
    """Gradient-descent-from-scratch results for the 'Two Roads, One Answer' section.

    The honest headline: the two methods agree on PREDICTIONS but not yet on WEIGHTS.
    fuel_bill is by construction ~ fuel_consumption_litres x fuel_price, so the design
    matrix is near-collinear, the loss surface is a long narrow valley, and gradient
    descent crawls along the flat direction. This is the same ill-conditioning the
    notebook flags in section 3.2 - surfaced rather than hidden.
    """
    gd = BUNDLE["gradient_descent"]
    converged = gd["epochs_used"] < 60_000
    return {
        "curve": gd["loss_curve"],
        "epochs_used": gd["epochs_used"],
        "converged": converged,
        "final_loss": gd["final_loss"],
        "max_weight_gap": gd["max_weight_gap"],
        "max_prediction_gap": gd["max_prediction_gap"],
        "r2_sklearn": gd["r2_sklearn"],
        "r2_gradient_descent": gd["r2_gradient_descent"],
        "features": BUNDLE["reg_features"],
        "weights": {
            "sklearn": gd["sklearn_weights"],
            "gradient_descent": gd["weights"],
        },
        "verdict": (
            "Predictions agree to within Rs {:.2f} and R2 matches to five decimals, but the "
            "weights have not converged after {:,} epochs. fuel_bill is almost exactly "
            "fuel_consumption_litres x fuel_price, so those columns are near-collinear: many "
            "different weight combinations fit equally well and gradient descent drifts slowly "
            "along that flat direction. sklearn jumps straight to one solution via the normal "
            "equations. Both are correct; they simply pick different points in the valley."
        ).format(gd["max_prediction_gap"], gd["epochs_used"]),
    }


@app.get("/api/default-mileage")
def default_mileage_endpoint(vehicle: VehicleType = "Sedan", fuel: FuelType = "Petrol"):
    """What the mileage sub-model predicts for this vehicle and fuel.

    Exists so the interface can prefill the mileage field with a figure that came from a model
    instead of a single hardcoded 15.5 for every car. The user can still override it, and the
    prediction response reports which of the two was used via `inputs.mileage_source`.
    """
    return {
        "vehicle_type": vehicle,
        "fuel_type": fuel,
        "mileage": default_mileage(vehicle, fuel),
        "source": "mileage_model",
        "note": ("Predicted from vehicle and fuel type. The training data draws mileage "
                 "uniformly inside a per-combination range, so this is the middle of the "
                 "right range, not your particular car - override it if you know better."),
    }


@app.get("/api/cities")
def search_cities(q: str = Query("", max_length=64), limit: int = Query(12, ge=1, le=50)):
    """Autocomplete over the 537 in-domain cities. Prefix matches rank above substring matches."""
    term = q.strip().lower()
    if not term:
        top = IN_DOMAIN.nlargest(limit, "population")
    else:
        mask = (IN_DOMAIN.city.str.lower().str.contains(term, regex=False)
                | IN_DOMAIN.state.str.lower().str.contains(term, regex=False))
        hits = IN_DOMAIN[mask].copy()
        hits["rank"] = np.where(hits.city.str.lower().str.startswith(term), 0, 1)
        top = hits.sort_values(["rank", "population"], ascending=[True, False]).head(limit)
    return {
        "count": int(len(top)),
        "results": [
            {"city": r.city, "state": r.state, "lat": float(r.lat),
             "lon": float(r.lon), "population": int(r.population),
             "fuel_prices": state_fuel_prices(r.state)}
            for r in top.itertuples(index=False)
        ],
    }


@app.post("/api/predict")
def predict(req: PredictRequest):
    origin = resolve_city(req.start_city, req.start_state)
    dest = resolve_city(req.destination_city, req.destination_state)
    if (origin.city, origin.state) == (dest.city, dest.state):
        raise HTTPException(400, "Start and destination must be different cities.")

    distance, distance_source = road_distance_km(
        float(origin.lat), float(origin.lon), float(dest.lat), float(dest.lon)
    )

    traffic = req.traffic_level
    traffic_inferred = traffic is None
    if traffic_inferred:
        traffic = predict_traffic(req.departure_hour, req.month)

    fuel_price, price_source = fuel_price_for(origin.state, req.fuel_type, req.fuel_price)
    parking = DEFAULT_PARKING if req.parking_cost is None else req.parking_cost

    # Sub-model 2 fills this in when the user does not know their own fuel efficiency.
    mileage_source = "user" if req.mileage is not None else "mileage_model"
    mileage = (req.mileage if req.mileage is not None
               else default_mileage(req.vehicle_type, req.fuel_type))

    litres, toll, total = estimate_cost(
        distance, mileage, fuel_price, parking, traffic, req.vehicle_type
    )

    band = predict_band(distance, mileage, fuel_price, toll, parking, litres,
                        req.vehicle_type, req.fuel_type, traffic)

    warnings: list[str] = []
    if not (MIN_TRAINED_KM <= distance <= MAX_TRAINED_KM):
        warnings.append(
            f"{distance:.0f} km is outside the model's training range "
            f"({MIN_TRAINED_KM:.0f}-{MAX_TRAINED_KM:.0f} km) - this estimate is extrapolating."
        )
    if distance_source == "haversine":
        warnings.append(
            "Routing service unavailable; distance is a calibrated straight-line estimate "
            "(haversine x 1.2355) and may differ from the real road distance."
        )
    # "user" is not a caveat — if someone typed the price they paid, there is nothing to warn
    # about. Only the table's own estimates and the fallback need disclosing.
    if price_source in ("estimated", "fallback"):
        warnings.append(
            f"Fuel price for {origin.state} is an estimate, not a measured price "
            f"(source: {price_source}). Enter the price at your pump for a firmer number."
        )

    # The error bar shown next to the prediction must describe THIS prediction. It used to be
    # BUNDLE["metrics"]["regression"]["mae"] = Rs 39.66, measured with the true toll, parking
    # and litres handed to the model - none of which the user supplied. The chained pipeline's
    # own held-out MAE is the honest figure, and it is an order of magnitude larger. Quoting
    # the small number beside a prediction that cannot achieve it is the exact dishonesty this
    # refactor set out to remove.
    served = PIPE["metrics"]["cost_chained"]
    fuel_component = round(litres * fuel_price, 2)
    maintenance = round(max(0.0, total - fuel_component - toll - parking), 2)

    return {
        "route": {
            "from": {"city": origin.city, "state": origin.state},
            "to": {"city": dest.city, "state": dest.state},
            "distance_km": distance,
            "distance_source": distance_source,
        },
        "inputs": {
            "vehicle_type": req.vehicle_type, "fuel_type": req.fuel_type,
            "mileage": mileage, "mileage_source": mileage_source,
            "fuel_price": fuel_price,
            "fuel_price_source": price_source, "parking_cost": parking,
            "departure_hour": req.departure_hour, "month": req.month,
            "passengers": req.passengers,
        },
        "derived": {
            "traffic_level": traffic,
            "traffic_inferred": traffic_inferred,
            "fuel_consumption_litres": litres,
            # The multiplier quoted here is read back out of the fitted litres model at
            # startup (see recovered_traffic_multipliers), not hardcoded. The model reproduces
            # the relationship to R2 = 1.000000, so the arithmetic shown is genuinely what it
            # computed - the string stays honest without pretending no model was involved.
            "fuel_consumption_explained": (
                f"{distance:.0f} km / {mileage} km/l x {TRAFFIC_MULT[traffic]} "
                f"({traffic.lower()} traffic) = {litres} L"
            ),
            "toll_cost": toll,
            "estimated_time_minutes": round(distance * TRAFFIC_MIN_PER_KM[traffic], 1),
        },
        "prediction": {
            "total_trip_cost": round(total, 2),
            "typical_error": round(served["mae"], 2),
            "typical_error_note": (
                "Mean absolute error of the chained pipeline on held-out trips. Most of it is "
                "toll and parking, which are not predictable from anything a traveller knows "
                "before setting off."
            ),
            "cost_per_km": round(total / distance, 2),
            "cost_per_passenger": round(total / req.passengers, 2),
            "cost_band": band,
            "breakdown": {
                "fuel": fuel_component, "toll": toll,
                "parking": parking, "wear_and_tear": maintenance,
            },
        },
        "warnings": warnings,
    }


if os.path.isdir(STATIC_DIR):
    app.mount("/", StaticFiles(directory=STATIC_DIR, html=True), name="static")
