"""
Road Trip Cost Predictor - FastAPI backend.

You tell it how far you are driving, what fuel costs where you are, and what you expect to pay
for parking. It prices the trip for a hatchback, a sedan and an SUV at once, on all three fuels,
so the comparison is the answer rather than something you have to run three times to get.

Every quantity you are NOT asked for is predicted by a fitted sub-model that reports its own
error bar - the litres you will burn, the tolls you will pay, and the km/l each vehicle manages.
Nothing in the prediction path is a number typed in by hand.

The distance is yours to supply because it is the one input you can look up exactly. The site
ships a reference table of measured road distances between 139 cities; /api/distance covers
anything not in it.

    python scripts/build_cities.py            # cities with real lat/lon
    python scripts/build_fuel_prices.py       # per-state fuel prices
    python scripts/build_wide_dataset.py      # 25,000 trips
    python scripts/fetch_real_distances.py    # 840 REAL road distances from OSRM
    python scripts/build_distance_matrix.py   # -> frontend/public/city_distances.json
    python scripts/train_pipeline.py          # -> models/pipeline.joblib  (the sub-models)
    python scripts/train_models.py            # -> models/model.joblib     (band + loss curve)
    uvicorn app:app --reload                  # -> http://127.0.0.1:8000

Endpoints
    GET  /api/cities             city search, for the distance lookup
    GET  /api/distance           measured road distance between two cities
    GET  /api/default-mileage    what each vehicle manages on a given fuel
    POST /api/predict            cost for every vehicle and fuel, with a breakdown
    GET  /api/loss-curve         gradient-descent curve + closed-form comparison
    GET  /api/metrics            honest test-set metrics for the report-card section
    GET  /api/health             liveness
"""
from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from functools import lru_cache
from typing import Literal, Optional

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

import roadtrip_features as rf

ROOT = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(ROOT, "models", "model.joblib")
PIPELINE_PATH = os.path.join(ROOT, "models", "pipeline.joblib")
CITIES_PATH = os.path.join(ROOT, "data", "india_cities.csv")
FUEL_PATH = os.path.join(ROOT, "data", "fuel_prices.csv")
STATIC_DIR = os.path.join(ROOT, "static")

# The distance range the cost model was trained across. Outside it the estimate is
# extrapolating, and the response says so rather than quietly returning a number. Because
# distance now arrives as a typed value rather than being derived from two real cities, the
# Pydantic bounds below are the real guard; this pair only controls the warning.
MIN_TRAINED_KM, MAX_TRAINED_KM = 50.0, 1500.0

OSRM_URL = "http://router.project-osrm.org/route/v1/driving/{},{};{},{}?overview=false"
OSRM_TIMEOUT = 4.0

VehicleType = Literal["Hatchback", "Sedan", "SUV"]
FuelType = Literal["Petrol", "Diesel", "CNG"]
VEHICLES: tuple[str, ...] = ("Hatchback", "Sedan", "SUV")
FUELS: tuple[str, ...] = ("Petrol", "Diesel", "CNG")

app = FastAPI(title="Road Trip Cost Predictor", version="2.0")
app.add_middleware(
    CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"]
)

# joblib.load unpickles, so it must only ever be pointed at files this repo produces itself.
# Both paths below are generated by scripts/ in this project and committed alongside it; no
# model file is ever fetched from a remote or user-supplied location.
#
#   BUNDLE  models/model.joblib     - the cost-band classifier and the gradient-descent history
#                                     that /api/loss-curve serves.
#   PIPE    models/pipeline.joblib  - the sub-models (distance, mileage, litres, toll) and the
#                                     chained cost regressor trained on their predictions.
BUNDLE = joblib.load(MODEL_PATH)
PIPE = joblib.load(PIPELINE_PATH)
CITIES = pd.read_csv(CITIES_PATH)
FUEL = pd.read_csv(FUEL_PATH).set_index("state")

# The models were trained on cities with population >= 100k; only those are in-domain.
IN_DOMAIN = CITIES[CITIES.population >= 100_000].reset_index(drop=True)
CITY_INDEX = {
    (r.city.lower(), r.state.lower()): r for r in IN_DOMAIN.itertuples(index=False)
}

# Used only to prefill the price fields, never inside a prediction that the user has priced
# themselves. Whatever they type wins, and the response labels which of the two produced each
# figure so an unedited field is never passed off as a real pump price.
NATIONAL_PRICE = {
    "Petrol": round(float(FUEL.petrol.mean()), 2),
    "Diesel": round(float(FUEL.diesel.mean()), 2),
    "CNG": round(float(FUEL.cng.mean()), 2),
}


# --------------------------------------------------------------------------- helpers
def model_distance_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Road distance from the fitted distance model - the offline path for /api/distance.

    Trained on 840 real OSRM road distances (data/real_distances.csv), so it has seen Indian
    road geometry rather than assuming a fixed ratio to the straight line. It predicts the
    ratio and multiplies by haversine, which keeps the target scale-free.
    """
    x = np.array([rf.distance_features(lat1, lon1, lat2, lon2)], dtype=float)
    predicted = float(PIPE["distance_model"].predict(x)[0])
    if PIPE["distance_parameterisation"] == "factor":
        predicted *= rf.haversine(lat1, lon1, lat2, lon2)
    return round(predicted, 2)


@lru_cache(maxsize=4096)
def road_distance_km(lat1: float, lon1: float, lat2: float, lon2: float) -> tuple[float, str]:
    """Measured road distance via OSRM, falling back to the fitted model.

    Live routing is preferred - a measured answer beats a predicted one whenever it is
    available. When it is not, the fallback is a model whose held-out error is known
    (RMSE 46.6 km, MAE 30.7 km), and the response says which of the two produced the number.
    """
    try:
        url = OSRM_URL.format(lon1, lat1, lon2, lat2)
        req = urllib.request.Request(url, headers={"User-Agent": "roadtrip-predictor/1.0"})
        with urllib.request.urlopen(req, timeout=OSRM_TIMEOUT) as resp:
            payload = json.loads(resp.read())
        if payload.get("code") == "Ok" and payload.get("routes"):
            return round(payload["routes"][0]["distance"] / 1000.0, 2), "measured"
    except (urllib.error.URLError, TimeoutError, ValueError, KeyError, OSError):
        pass  # network unavailable or rate-limited - fall through to the model
    return model_distance_km(lat1, lon1, lat2, lon2), "distance_model"


def default_mileage(vehicle: str, fuel: str) -> float:
    """Fuel efficiency from the mileage sub-model.

    This is what makes pricing three vehicles at once mean anything. A single typed mileage
    cannot describe a hatchback and an SUV at the same time, so each vehicle gets its own
    figure, and the difference between those figures is most of the difference in cost.

    Honest ceiling: the training data draws mileage uniformly inside a per-combination range,
    so this is the middle of the right range rather than any particular car - test R2 0.673,
    and the rest is irreducible. The user can override it per vehicle.
    """
    x = np.array([rf.mileage_features(vehicle, fuel)], dtype=float)
    return round(float(PIPE["mileage_model"].predict(x)[0]), 2)


def predict_litres(distance: float, mileage: float) -> float:
    """Fuel consumed over the trip, from the litres sub-model."""
    x = np.array([rf.litres_features(distance, mileage)], dtype=float)
    return round(float(PIPE["litres_model"].predict(x)[0]), 3)


def predict_toll(distance: float) -> float:
    """Toll, from the toll sub-model.

    Honest ceiling: toll in the training data carries a per-trip spread around its rate, so the
    rate is recoverable but the spread is not. Test R2 0.795, and the residual RMSE of about
    Rs 212 cannot be reduced by any model on this data.
    """
    x = np.array([rf.toll_features(distance)], dtype=float)
    return round(max(0.0, float(PIPE["toll_model"].predict(x)[0])), 2)


@lru_cache(maxsize=8)
def fuel_burn_slope() -> float:
    """The litres model's fitted slope on (distance / mileage), recovered by probing it.

    The interface prints the arithmetic behind the litres figure, and that line has to equal
    the number beside it. Writing "distance / mileage = litres" would assert a slope of exactly
    1.0, which is not what the model fitted - real driving burns more than the rated figure.
    Probing at two ratios recovers the real slope, so the printed sum is the one computed.
    """
    mileage = 15.0
    one = predict_litres(mileage * 1.0, mileage)      # ratio = 1
    two = predict_litres(mileage * 2.0, mileage)      # ratio = 2
    return round(two - one, 4)


def resolve_city(name: str, state: Optional[str] = None):
    key_name = name.strip().lower()
    if state:
        hit = CITY_INDEX.get((key_name, state.strip().lower()))
        if hit is not None:
            return hit
    matches = IN_DOMAIN[IN_DOMAIN.city.str.lower() == key_name]
    if matches.empty:
        raise HTTPException(404, f"City not found: {name!r}")
    # ambiguous name -> largest city wins
    return matches.sort_values("population", ascending=False).iloc[0]


def state_fuel_prices(state: str) -> dict:
    """All three prices for a state, so the lookup page can offer them as a starting point."""
    if state in FUEL.index:
        row = FUEL.loc[state]
        return {
            "petrol": float(row["petrol"]), "diesel": float(row["diesel"]),
            "cng": float(row["cng"]), "source": str(row["source"]),
        }
    return {"petrol": NATIONAL_PRICE["Petrol"], "diesel": NATIONAL_PRICE["Diesel"],
            "cng": NATIONAL_PRICE["CNG"], "source": "national average"}


def predict_band(distance, mileage, fuel_price, toll, parking, litres,
                 vehicle: str, fuel: str) -> str:
    """Is this trip cheap or expensive FOR ITS LENGTH? A quartile split of Rs/km.

    Rupees alone cannot answer that question - a 1200 km drive costs more than a 200 km one
    without being worse value - so the band is what the result cards carry alongside the total.
    """
    frame = pd.DataFrame([{
        "distance_km": distance, "mileage": mileage, "fuel_price": fuel_price,
        "toll_cost": toll, "parking_cost": parking, "fuel_consumption_litres": litres,
        "vehicle_type": vehicle, "fuel_type": fuel,
    }])
    encoded = pd.get_dummies(frame, columns=BUNDLE["band_categorical"], drop_first=True)
    encoded = encoded.reindex(columns=BUNDLE["band_columns"], fill_value=0)
    scaled = BUNDLE["band_scaler"].transform(encoded.values.astype(float))
    return str(BUNDLE["band_classifier"].predict(scaled)[0])


def price_one(distance: float, vehicle: str, fuel: str, price: float,
              parking: float, passengers: int, mileage: Optional[float]) -> dict:
    """One vehicle on one fuel. Every field a result card shows comes from here."""
    mileage_source = "user" if mileage is not None else "mileage_model"
    km_per_litre = mileage if mileage is not None else default_mileage(vehicle, fuel)

    litres = predict_litres(distance, km_per_litre)
    toll = predict_toll(distance)
    x = np.array([rf.cost_features(distance, km_per_litre, price, toll, parking,
                                   litres, vehicle)], dtype=float)
    total = float(PIPE["cost_model_chained"].predict(x)[0])

    fuel_component = round(litres * price, 2)
    # Whatever the model's total does not account for as fuel, toll or parking is the running
    # cost of the vehicle itself. Clamped at zero so a rounding artefact cannot show as negative.
    running = round(max(0.0, total - fuel_component - toll - parking), 2)

    return {
        "vehicle_type": vehicle,
        "fuel_type": fuel,
        "mileage": km_per_litre,
        "mileage_source": mileage_source,
        "fuel_price": price,
        "total_trip_cost": round(total, 2),
        "cost_per_km": round(total / distance, 2),
        "cost_per_passenger": round(total / passengers, 2),
        "cost_band": predict_band(distance, km_per_litre, price, toll, parking,
                                  litres, vehicle, fuel),
        "fuel_consumption_litres": litres,
        "fuel_consumption_explained": (
            f"{distance:.0f} km / {km_per_litre} km/l x {fuel_burn_slope()} "
            f"(real-world driving) = {litres} L"
        ),
        "toll_cost": toll,
        "breakdown": {
            "fuel": fuel_component, "toll": toll,
            "parking": parking, "running_cost": running,
        },
    }


# ---------------------------------------------------------------------------- schemas
class PredictRequest(BaseModel):
    """What the form collects. Anything absent here is predicted, not assumed.

    extra="forbid" matters more than it looks: without it a stale client posting fields this
    API no longer reads would get a confident 200 back, computed from inputs it believed were
    honoured and were silently dropped. A 422 is the kinder failure.
    """
    model_config = {"extra": "forbid"}

    # Bounds, not warnings. Distance used to be derived from two real cities, which made a sane
    # value structurally guaranteed; a typed box guarantees nothing. At 0 the cost-per-km divides
    # by zero, below about 10 km the toll model is outside anything it ever saw, and with no
    # ceiling a stray keypress extrapolates linearly into six figures without erroring.
    distance_km: float = Field(
        ..., gt=10, le=3000,
        description="road distance in km - look it up on the distance page",
    )
    petrol_price: Optional[float] = Field(None, gt=30, lt=300)
    diesel_price: Optional[float] = Field(None, gt=30, lt=300)
    cng_price: Optional[float] = Field(None, gt=30, lt=300,
                                       description="rupees per kg for CNG")
    parking_cost: float = Field(70, ge=0, le=2000)
    passengers: int = Field(4, ge=1, le=8)
    mileage: Optional[dict[VehicleType, float]] = Field(
        None,
        description='per-vehicle km/l override, e.g. {"SUV": 12.5}. Omit a vehicle and the '
                    'mileage sub-model fills it in.',
    )


# ----------------------------------------------------------------------------- routes
@app.get("/api/health")
def health():
    return {"status": "ok", "cities": len(IN_DOMAIN), "model": os.path.basename(MODEL_PATH)}


@app.get("/api/metrics")
def metrics():
    """Honest test-set numbers. The UI shows these verbatim - do not round them up.

    Two numbers get reported because there are two different questions, and only one of them is
    the user's. `served` is what a prediction from this API is worth. `fed_true_components` is
    the same regressor handed the litres actually burnt and the toll actually paid - it scores
    far higher and it answers a question nobody can ask, because those are exactly the figures
    you cannot know before setting off. Quote `served`.
    """
    pm = PIPE["metrics"]
    m = dict(BUNDLE["metrics"])

    served = pm["cost_chained"]
    fed = pm["cost_true_components"]
    m["served"] = {
        "what": "distance + fuel price + parking in, a cost for every vehicle out",
        "r2": served["r2"], "rmse": served["rmse"], "mae": served["mae"],
        "note": "This is what a prediction from this API is worth.",
    }
    m["fed_true_components"] = {
        "what": "the same cost regressor, given the true toll and litres",
        "r2": fed["r2"], "rmse": fed["rmse"], "mae": fed["mae"],
        "note": ("Reported for contrast, not as a headline. It answers 'given the litres burnt "
                 "and the toll paid, can you add them up?' - which is not the user's question."),
    }
    m["honesty_gap"] = {
        "r2": round(fed["r2"] - served["r2"], 6),
        "mae_rupees": round(served["mae"] - fed["mae"], 2),
        "note": ("What it costs to derive the two inputs nobody can supply, instead of being "
                 "handed them. This gap IS the finding, not an embarrassment."),
    }
    m["sub_models"] = {
        "distance": {
            "trained_on": f"{pm['n_real_distance_pairs']} real OSRM road distances",
            "r2": pm["distance_real"]["r2"], "rmse_km": pm["distance_real"]["rmse"],
            "mae_km": pm["distance_real"]["mae"],
            "fixed_ratio_baseline_mae_km": pm["distance_constant_baseline"]["mae"],
            "note": ("The only model here trained on observed rather than generated data. It "
                     "fills in road distances the reference table does not cover."),
        },
        "litres": {
            "r2": pm["litres"]["r2"], "rmse_litres": pm["litres"]["rmse"],
            "fitted_ratio_slope": pm["litres_ratio_slope"],
            "note": ("The slope sits above 1.0 because real driving burns more than "
                     "distance / mileage. How much more depends on conditions nobody can state "
                     "in advance, so the model learns the average and carries the rest as "
                     "error - the largest single term in the budget below."),
        },
        "parking": {
            "best_r2": pm["parking_negative_result"]["best_r2"],
            "note": ("NEGATIVE RESULT: six model families all scored test R2 <= 0, worse than "
                     "predicting the mean. Nothing in the inputs predicts parking, which is "
                     "why it is asked for rather than guessed."),
        },
        "error_budget": pm["error_budget"],
    }
    m["distance_convention_gap"] = pm["distance_convention_gap"]
    m["notes"] = {
        "regression": ("Linear regression including the litres x price and distance x vehicle "
                       "interaction terms."),
        "band": ("cost_band is a quartile split of Rs/km, which the regressor already predicts "
                 "well, so this accuracy is partly high by construction."),
        "served_vs_fed": ("Quote `served`. `fed_true_components` is the larger number and it "
                          "measures a different question."),
    }
    return m


@app.get("/api/loss-curve")
def loss_curve():
    """Gradient-descent-from-scratch results, against the closed-form solution.

    The honest headline: the two methods agree on PREDICTIONS but not on WEIGHTS. fuel_bill is
    by construction ~ litres x price, so the design matrix is near-collinear, the loss surface
    is a long narrow valley, and gradient descent crawls along the flat direction. Surfaced
    rather than hidden.
    """
    gd = BUNDLE["gradient_descent"]
    converged = gd["epochs_used"] < 60_000
    return {
        "curve": gd["loss_curve"],
        "epochs_used": gd["epochs_used"],
        "converged": converged,
        "final_loss": gd["final_loss"],
        "max_weight_gap": gd["max_weight_gap"],
        "max_prediction_gap": gd["max_prediction_gap"],
        "r2_sklearn": gd["r2_sklearn"],
        "r2_gradient_descent": gd["r2_gradient_descent"],
        "features": BUNDLE["reg_features"],
        "weights": {
            "sklearn": gd["sklearn_weights"],
            "gradient_descent": gd["weights"],
        },
        "verdict": (
            "Predictions agree to within Rs {:.2f} and R2 matches to five decimals, but the "
            "weights have not converged after {:,} epochs. fuel_bill is almost exactly "
            "fuel_consumption_litres x fuel_price, so those columns are near-collinear: many "
            "different weight combinations fit equally well and gradient descent drifts slowly "
            "along that flat direction. The closed form jumps straight to one solution via the "
            "normal equations. Both are correct; they simply pick different points in the "
            "valley."
        ).format(gd["max_prediction_gap"], gd["epochs_used"]),
    }


@app.get("/api/default-mileage")
def default_mileage_endpoint(fuel: FuelType = "Petrol"):
    """What each of the three vehicles manages on this fuel, from the mileage sub-model.

    The form prefills from this rather than asking for a number nobody knows offhand, and it
    returns all three at once because the result prices all three at once.
    """
    return {
        "fuel_type": fuel,
        "mileage": {v: default_mileage(v, fuel) for v in VEHICLES},
        "source": "mileage_model",
        "note": ("Predicted from vehicle and fuel type. The training data draws mileage "
                 "uniformly inside a per-combination range, so this is the middle of the "
                 "right range, not your particular car - override it if you know better."),
    }


@app.get("/api/cities")
def search_cities(q: str = Query("", max_length=64), limit: int = Query(12, ge=1, le=50)):
    """Autocomplete over the in-domain cities, for the distance lookup."""
    term = q.strip().lower()
    if not term:
        top = IN_DOMAIN.nlargest(limit, "population")
    else:
        mask = (IN_DOMAIN.city.str.lower().str.contains(term, regex=False)
                | IN_DOMAIN.state.str.lower().str.contains(term, regex=False))
        hits = IN_DOMAIN[mask].copy()
        hits["rank"] = np.where(hits.city.str.lower().str.startswith(term), 0, 1)
        top = hits.sort_values(["rank", "population"], ascending=[True, False]).head(limit)
    return {
        "count": int(len(top)),
        "results": [
            {"city": r.city, "state": r.state, "lat": float(r.lat),
             "lon": float(r.lon), "population": int(r.population),
             "fuel_prices": state_fuel_prices(r.state)}
            for r in top.itertuples(index=False)
        ],
    }


@app.get("/api/distance")
def distance_between(
    origin: str = Query(..., alias="from", max_length=64),
    destination: str = Query(..., alias="to", max_length=64),
    origin_state: Optional[str] = Query(None, alias="from_state", max_length=64),
    destination_state: Optional[str] = Query(None, alias="to_state", max_length=64),
):
    """Road distance between two cities, for routes the shipped reference table does not cover.

    Tries live routing first and falls back to the fitted distance model, reporting which one
    answered. `straight_line_km` comes back alongside so the gap between the two is visible:
    the ratio between them is not a constant, which is the reason a model sits here at all.
    """
    a = resolve_city(origin, origin_state)
    b = resolve_city(destination, destination_state)
    if (a.city, a.state) == (b.city, b.state):
        raise HTTPException(400, "Start and destination must be different cities.")

    km, source = road_distance_km(float(a.lat), float(a.lon), float(b.lat), float(b.lon))
    straight = round(rf.haversine(float(a.lat), float(a.lon), float(b.lat), float(b.lon)), 2)
    return {
        "from": {"city": a.city, "state": a.state},
        "to": {"city": b.city, "state": b.state},
        "distance_km": km,
        "straight_line_km": straight,
        "winding_ratio": round(km / straight, 3) if straight else None,
        "source": source,
        "fuel_prices": {"from": state_fuel_prices(a.state), "to": state_fuel_prices(b.state)},
        "in_trained_range": MIN_TRAINED_KM <= km <= MAX_TRAINED_KM,
    }


@app.post("/api/predict")
def predict(req: PredictRequest):
    """Price the trip for every vehicle on every fuel.

    All nine combinations come back in one response rather than one request each. That lets the
    interface switch fuel and compare vehicles without another round trip, and - more to the
    point - a single request cannot race itself the way three concurrent ones can.
    """
    distance = req.distance_km
    overrides = req.mileage or {}

    supplied = {"Petrol": req.petrol_price, "Diesel": req.diesel_price, "CNG": req.cng_price}
    prices = {f: (supplied[f] if supplied[f] is not None else NATIONAL_PRICE[f]) for f in FUELS}
    price_sources = {f: ("user" if supplied[f] is not None else "national_average")
                     for f in FUELS}

    results = {
        fuel: [price_one(distance, vehicle, fuel, prices[fuel], req.parking_cost,
                         req.passengers, overrides.get(vehicle))
               for vehicle in VEHICLES]
        for fuel in FUELS
    }

    flat = [row for rows in results.values() for row in rows]
    cheapest = min(flat, key=lambda r: r["total_trip_cost"])
    dearest = max(flat, key=lambda r: r["total_trip_cost"])

    warnings: list[str] = []
    if not (MIN_TRAINED_KM <= distance <= MAX_TRAINED_KM):
        warnings.append(
            f"{distance:.0f} km is outside the range the model was trained on "
            f"({MIN_TRAINED_KM:.0f}-{MAX_TRAINED_KM:.0f} km) - this estimate is extrapolating."
        )
    estimated = [f for f in FUELS if price_sources[f] == "national_average"]
    if estimated:
        warnings.append(
            f"{', '.join(estimated)} priced at the national average rather than a figure you "
            f"gave us. Enter the price at your pump for a firmer number."
        )

    # The error bar shown beside a prediction must describe THIS prediction. It is the chained
    # pipeline's own held-out MAE, not the far smaller figure the regressor scores when it is
    # handed the true toll and litres - quoting that one next to a number that cannot achieve
    # it would be dishonest.
    served = PIPE["metrics"]["cost_chained"]

    return {
        "inputs": {
            "distance_km": distance,
            "parking_cost": req.parking_cost,
            "passengers": req.passengers,
            "fuel_prices": prices,
            "fuel_price_sources": price_sources,
        },
        "results": results,
        "cheapest": {k: cheapest[k] for k in ("vehicle_type", "fuel_type", "total_trip_cost")},
        "dearest": {k: dearest[k] for k in ("vehicle_type", "fuel_type", "total_trip_cost")},
        "max_saving": round(dearest["total_trip_cost"] - cheapest["total_trip_cost"], 2),
        "prediction": {
            "typical_error": round(served["mae"], 2),
            "typical_error_note": (
                "Mean absolute error of the chained pipeline on held-out trips. Most of it is "
                "toll and real-world fuel burn, neither of which is predictable from anything "
                "a traveller knows before setting off."
            ),
        },
        "warnings": warnings,
    }


if os.path.isdir(STATIC_DIR):
    app.mount("/", StaticFiles(directory=STATIC_DIR, html=True), name="static")
